title: "StyleSVC:Fine-grained Style Transfer for Singing Voice Conversion"
# description: Cayman is a clean, responsive theme for GitHub Pages.
# show_downloads: true
# google_analytics:
theme: jekyll-theme-cayman
markdown: kramdown
layout: default
kramdown:
  toc_levels: 1..2
